### ISSUE TITLE
Structure Block Import Issue

### ISSUE THREAD

**Issue by Topsangtheman** [MRBBATES1/StructureImports#1]
Hello it's me again, here's the pack contining the .mcstructure files. It is compressed.

[Uploading more_structures_addon.zip…]()

**Comment by MRBBATES1** [comment]
I will take a look as soon as I can and let you know

**Comment by MRBBATES1** [comment]
@Topsangtheman 

it seems the link doesnt work, i click on it and it just refreshes the page, doesnt seem to download anything. Goto the below site, upload it there:

https://wetransfer.com/

instead of adding an email address, click on the 3 dots and change to 'Get Transfer Link'. Once your file is uploaded it should provide a URL which you can paste back here. I should then be able to download it.

**Comment by MRBBATES1** [comment]
i have not received anything from you so this issue is being closed
